# Generated by Django 5.0.6 on 2024-06-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_accountinformation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='موضوع ')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس اینترنتی این پست')),
                ('description', models.TextField(verbose_name='توضیحات این پست')),
            ],
            options={
                'verbose_name_plural': 'پست ها ',
                'db_table': 'blog',
            },
        ),
    ]
