# Generated by Django 5.0.6 on 2024-06-21 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.accountinformation', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('public', 'منتشر شود')], default='draft', max_length=10, null=True, verbose_name='وضعیت انتشار این پست'),
        ),
    ]
