# Generated by Django 5.0.6 on 2024-06-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_blog_author_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(verbose_name='آدرس اینترنتی این پست'),
        ),
    ]
