# Generated by Django 5.0.6 on 2024-06-17 06:23

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='person',
            name='hb',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
    ]
