# Generated by Django 5.0.6 on 2024-06-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_course_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'درس'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'معلم'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'دانش آموز'},
        ),
    ]
